name: example

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name:
                Install cowsay Program
              run:
                sudo apt-get install cowsay -y
            - name: Exucute Cowsay CMD
              run: cowsay -f dragon "Runn for cover, I am Dragon" >> dragon.txt
            - uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: dragon.txt
              
            
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@v4
            with:
              name: my-artifact
              path: dragon.txt
          - name: show file
            run: cat dragon.txt