name: example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name:
                Install cowsay Program
              run:
                sudo apt-get install cowsay -y
            - name: Exucute Cowsay CMD
              run: cowsay -f dragon "Runn for cover, I am Dragon" >> dragon.txt
            - name: show file
              run: cat dragon.txt